### ISSUE TITLE
Move old blueprints into this repository

### ISSUE THREAD

**Issue by ifraixedes** [storj/design-docs#8]
### Motivation/Why?

We want a single to find all the relevant information about the design of all the systems related to Storj.

### What needs to be done?

- Take all the blueprint documents in [storj repository](https://github.com/storj/storj) that are still applicable (code and logic that remains) and add them to the root of this repository.
- Rename those documents to prefix them with the initial commit date with the format specified in the conventions present in the README.
- Add a frontmatter with the required fields specified in the conventions present in the README.
- Documents that aren't applicable, place them in a folder in the root named `archived`.

### Acceptance criteria

- Add all the blueprint documents in [storj repository](https://github.com/storj/storj) to this repository.
- Once they are in, delete those documents from the [storj repository](https://github.com/storj/storj).

**Comment by shaupt131** [comment]
This is a good cleanup task to get done.  Let's plan on doing this during sprint 29.

**Comment by ifraixedes** [comment]
Related commit to delete the documents from the storj/storj repo https://review.dev.storj.io/c/storj/storj/+/12050

**Comment by ifraixedes** [comment]
The only part that's missing is to move documents to `archived`, but, I don't know which ones should be there, so if somebody know, let me know in the review of #12  and I will move them
